### ISSUE TITLE
Set up Jest for front-end and back-end

### ISSUE THREAD

**Issue by sfiquet** [chingu-voyage4/Bears-Team-19#24]
To do:
- [x] investigate how to use Jest within React
- [x] set up testing for React app
- [x] investigate how to set up Jest for the Express app
- [x] set up testing for Express app
- [x] document how to use Jest in the development workflow

**Comment by sfiquet** [comment]
I set up Jest and Enzyme for the client during task #31.

**Comment by Heyjp** [comment]
Up for review on #63

**Comment by sfiquet** [comment]
Closed with #63
